---
- name: wireguard client
  hosts: all
  tasks:

    - name: Packages for wireguard
      apt:
        name:
          - wireguard
          - network-manager
        update_cache: no
        install_recommends: no

    - name: activate wireguard logging
      blockinfile:
        path: /etc/modprobe.d/wireguard.conf
        create: yes
        mode: "0444"
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK for wireguard"
        insertbefore: BOF
        block: |
          options wireguard dyndbg=+p
          
    - name: load wireguard module during boot
      blockinfile:
        path: /etc/modules-load.d/wireguard.conf
        create: yes
        mode: "0444"
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK for wireguard"
        insertbefore: BOF
        block: |
          wireguard
          
    - name: /usr/local/sbin/wireguard.sh
      blockinfile:
        path: /usr/local/sbin/wireguard.sh
        create: yes
        mode: 0500
        owner: root
        group: root
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          . /etc/bash/gaboshlib.include

          g_lockfile

          # first let dnstest.sh run
          sleep 10       
   
          wireguard_config="/usr/local/etc/wg-client.conf"
          if ! [ -s $wireguard_config ]
          then
            g_echo "No wireguard configuration in $wireguard_config"
            exit 0
          fi

          while [[ -s /var/lock/dnstest.sh.lock ]]
          do
            g_echo "Waiting for /var/lock/dnstest.sh.lock"
            sleep 1
          done

          [ -s $wireguard_config ] || exit 0

          wgdnsip=$(grep "^DNS" $wireguard_config | cut -d= -f2 | cut -d, -f1)
          if ping -c3 $wgdnsip >/dev/null 2>&1
          then
            g_echo "wireguard connection OK"
            exit 0
          fi

          g_echo "No wireguard connection"

          wghost=$(grep "^Endpoint" $wireguard_config | cut -d= -f2 | cut -d: -f1)
          if ! host -W5 $wghost
          then
            g_echo_warn "DNS for $wghost not working"
            # maybe vpn is blocking dns - if active remove
            if nmcli connection | grep -q " wg-client"
            then
              g_echo_warn "removing wg-client - maybe its blocking DNS/Internet access"
              nmcli connection down wg-client
              nmcli connection delete wg-client
            fi
            exit 1
          fi

          nmcli connection | grep -q "^wg-client" || \
          if ! nmcli connection import type wireguard file $wireguard_config
          then
            g_echo_error "Failed to import Wireguard VPN file $wireguard_config"
            exit 2
          fi

          # (re)connect wireguard if not deactivated in nm
          if nmcli connection | grep -q " wg-client"
          then
            g_echo_warn "reconnecting wg-client"
            nmcli connection down wg-client
            nmcli connection up wg-client
            exit 3
          fi
        backup: yes
        validate: /bin/bash -n %s

    - name: /usr/local/sbin/wireguard.sh shebang
      lineinfile:
        path: /usr/local/sbin/wireguard.sh
        insertbefore: BOF
        line: "#!/bin/bash"

    - name: Schedule WireGuard script in cron
      ansible.builtin.cron:
        name: "WireGuard Script"
        minute: "*"
        hour: "*"
        day: "*"
        month: "*"
        weekday: "*"
        user: "root"
        job: "/usr/local/sbin/wireguard.sh >>/var/log/wireguard.sh.log 2>&1"

