---
- name: dnscrypt-proxy2
  hosts: all
  gather_facts: no

  vars:
    openwrt_packages:
      - dnscrypt-proxy2
 
  tasks:
    - name: write /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
      raw: |
        cat << 'EOF' > /etc/dnscrypt-proxy2/dnscrypt-proxy.toml
        # Documentation https://github.com/DNSCrypt/dnscrypt-proxy/wiki

        # listen on all interfaces
        listen_addresses = ['127.0.0.55:53']

        # DoH server list
        server_names = ['doh.mullvad.net-194.242.2.2', 'doh.ffmuc.net-185.150.99.255', 'doh.ffmuc.net-5.1.66.255', 'dns.digitale-gesellschaft.ch-185.95.218.42', 'dns.digitale-gesellschaft.ch-185.95.218.43', 'anycast.uncensoreddns.org-91.239.100.100']

        # server names to avoid even if they match all criteria
        # disabled_server_names = []

        ## what kinds of server do we want to resolve from?
        doh_servers = true
        ipv4_servers = false
        ipv6_servers = false
        dnscrypt_servers = false

        # do we support IPv6 accressing?
        block_ipv6 = false

        # don't let weird queries & typos leak upstream
        block_unqualified = true
        block_undelegated = true

        # TTL for synthetic responses sent when a request has been blocked
        reject_ttl = 600

        # request DoH servers which offer DNSSEC / tamperproofing
        require_dnssec = true

        # we are using tor, so we should not care about logging
        require_nolog = false

        # request DoH servers that advertise themselves as unfiltered
        require_nofilter = true

        # use tor
        force_tcp = true
        proxy = 'socks5://127.0.0.1:9050'

        # how long (ms) a DNS query will wait for a response; reasonable max 10s
        timeout = 10000

        # keepalive for HTTP (HTTPS, HTTP/2) queries, in seconds; default: 30
        keepalive = 30

        # loadbalancing; p2 strategy, and continuous farming of the list
        lb_strategy = 'p2'
        lb_estimator = true

        # logging: approx 1 month of weekly logs, capped-out/force-rotated at 64Mb
        log_level = 2
        use_syslog = true
        #log_files_max_size = 64
        #log_files_max_age = 7
        #log_files_max_backups = 4

        # delay, in minutes, after which certificates are reloaded; this also
        # drives the latency logger, so we poll/log every hour
        cert_refresh_delay = 60

        # less linkability / more privacy at slight performance impact;
        # see the notes in the above-cited documentation
        tls_disable_session_tickets = true
        tls_cipher_suite = [52392, 49199]

        # for healthcheck, heartbeat and bootstrap, dnscrypt-proxy MUST be
        # able to probe the internet, so we must configure our firewall so
        # that it is the only one which can use port 53 to the internet;
        # dnscrypt-proxy claims that it will only use these services in very
        # limited circumstances. Regards option naming, see:
        # https://github.com/DNSCrypt/dnscrypt-proxy/commit/c500287498a05b07c3af8effa23a0ba4c42f00f1
        fallback_resolvers = ['46.182.19.48:53']
        netprobe_address = '46.182.19.48:53'
        netprobe_timeout = 60
        ignore_system_dns = true

        # explicit caching
        cache = true
        cache_size = 4096
        cache_min_ttl = 60
        cache_max_ttl = 86400
        cache_neg_min_ttl = 60
        cache_neg_max_ttl = 1800

        # I am not configuring this resolver as a local DoH listener, to do so
        # requires a TLS certificate and that's a world of pain

        [query_log]
        file = '/var/log/dnscrypt-proxy/query.log'
        # ignored_qtypes = ['DNSKEY', 'NS']

        [nx_log]
        file = '/var/log/dnscrypt-proxy/nx.log'

        [blocked_names]
        blocked_names_file = 'blocked-names.txt'
        log_file = '/var/log/dnscrypt-proxy/blocked-names.log'
                  
        [blocked_ips]
        # blocked_ips_file = 'blocked-ips.txt'
        # log_file = '/var/log/dnscrypt-proxy/blocked-ips.log'

        [allowed_names]
        # allowed_names_file = 'allowed-names.txt'
        # log_file = '/var/log/dnscrypt-proxy/allowed-names.log'
                  
        [allowed_ips]
        # allowed_ips_file = 'allowed-ips.txt'
        # log_file = '/var/log/dnscrypt-proxy/allowed-ips.log'

        # Static DoH DNS Servers from inspired by https://www.kuketz-blog.de/empfehlungsecke/#dns
        # Stamps from https://dnscrypt.info/stamps/
        [static]

        [static.'doh.mullvad.net-194.242.2.2']
        stamp = 'sdns://AgcAAAAAAAAACzE5NC4yNDIuMi4yAA9kb2gubXVsbHZhZC5uZXQKL2Rucy1xdWVyeQ'

        [static.'doh.ffmuc.net-185.150.99.255']
        stamp = 'sdns://AgcAAAAAAAAADjE4NS4xNTAuOTkuMjU1AA1kb2guZmZtdWMubmV0Ci9kbnMtcXVlcnk'

        [static.'doh.ffmuc.net-5.1.66.255']
        stamp = 'sdns://AgcAAAAAAAAACjUuMS42Ni4yNTUADWRvaC5mZm11Yy5uZXQKL2Rucy1xdWVyeQ'
         
        [static.'dns.digitale-gesellschaft.ch-185.95.218.42']
        stamp = 'sdns://AgcAAAAAAAAADTE4NS45NS4yMTguNDIAHGRucy5kaWdpdGFsZS1nZXNlbGxzY2hhZnQuY2gKL2Rucy1xdWVyeQ'

        [static.'dns.digitale-gesellschaft.ch-185.95.218.43']
        stamp = 'sdns://AgcAAAAAAAAADTE4NS45NS4yMTguNDMAHGRucy5kaWdpdGFsZS1nZXNlbGxzY2hhZnQuY2gKL2Rucy1xdWVyeQ'

        [static.'anycast.uncensoreddns.org-91.239.100.100']
        stamp = 'sdns://AgcAAAAAAAAADjkxLjIzOS4xMDAuMTAwABlhbnljYXN0LnVuY2Vuc29yZWRkbnMub3JnCi9kbnMtcXVlcnk'
        EOF
      changed_when: false

    - name: write, run and create cronjob /etc/scripts/dnscrypt-proxy-blocklist-update.sh
      raw: |
        mkdir -p /etc/scripts
        cat << 'EOF' > /etc/scripts/dnscrypt-proxy-blocklist-update.sh
        cd /etc/dnscrypt-proxy
        g_tmp=/tmp

        touch blocked-names-local-whitelist.txt
        chmod 660 blocked-names-local-whitelist.txt
        chown root: blocked-names-local-whitelist.txt
        # get hosts blocklist from https://github.com/StevenBlack/hosts
        for list in \
         https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts \
         https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling/hosts
        do
          target=$(echo $list | cut -d/ -f 8)
          wget $list -O - | grep "^0\.0\.0\.0 " | cut -d" " -f2 | grep "\." | egrep -v '^\.|\.$' | egrep -v -f blocked-names-local-whitelist.txt >${g_tmp}/blocked-names.txt
          numhosts=$(cat ${g_tmp}/blocked-names.txt | wc -l)
          if [ "$numhosts" -gt 50000 ]
          then
            cat ${g_tmp}/blocked-names.txt >blocked-names.txt
            cp -p blocked-names.txt "blocked-names-${target}.txt"
          else
            g_echo_error "Not enough lines in hosts blocklist from https://github.com/StevenBlack/hosts"
          fi
        done
        rm -f ${g_tmp}/blocked-names.txt
        touch blocked-names-local-additions.txt
        chmod 660 blocked-names-local-additions.txt
        chown root: blocked-names-local-additions.txt

        [ -s blocked-names-local-additions.txt ] && cat blocked-names-local-additions.txt >>blocked-names.txt
        /etc/init.d/dnscrypt-proxy restart
        EOF
        chmod 700 /etc/scripts/dnscrypt-proxy-blocklist-update.sh
        /etc/scripts/dnscrypt-proxy-blocklist-update.sh
        cronjob="15 6 * * *   /etc/scripts/dnscrypt-proxy-blocklist-update.sh"
        grep -Fq "$cronjob" /etc/crontabs/root || echo "$cronjob" >>/etc/crontabs/root

        ## Public doh servers
        wget -q https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/refs/heads/master/v3/public-resolvers.md -O - | grep '^sdns://' | sed 's#^sdns://##' | while read dns; do echo -n "$dns" | base64 -d 2>/dev/null | cut -d" " -f1; done | sed 's/[^[:print:]]/ /g ; s/^ *//' | egrep -a '^[0-9]|^\[' | cut -d" " -f1 | sed 's/:[[:digit:]]\+$//' | sed 's/[][]//g' | sort -u >/etc/doh-servers.txt.new
        
      changed_when: false

    - name: commit enable and restart
      raw: "{{ item }}"
      loop:
        - "/etc/init.d/dnscrypt-proxy restart"

