---
- name: allow to tor
  hosts: all
  gather_facts: no

  vars:
    uci_vars:
      ## rules
      - { key: "firewall.rule_forward_lan_{{ rule_name }}",           value: "rule" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.src",       value: "{{ src }}" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.dest",      value: "tor" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.target",    value: "ACCEPT" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.proto",     value: "{{ proto }}" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.name",      value: "ansible_forward_lan_{{ rule_name }}" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.dest_port", value: "{{ dest_port }}" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.src_ip",      value: "{{ src_ip }}" }
      - { key: "firewall.rule_forward_lan_{{ rule_name }}.dest_ip",     value: "{{ dest_ip }}" }

  tasks:

    - name: set uci values if needed
      raw: |
        current=$(uci get {{ item.key }} 2>/dev/null || echo "NOT_SET")
        desired="{{ item.value }}"
        [ -z "$desired"  ] && ( echo unchanged ; exit 0 )

        if [ "$current" != "$desired" ]
        then
          uci set {{ item.key }}="$desired"
          echo "changed"
        else
          echo "unchanged"
        fi
      loop: "{{ uci_vars }}"
      register: uci_set_result
      changed_when: "not 'unchanged' in uci_set_result.stdout"

    - name: apply changes
      block:
        - name: commit enable and restart
          raw: "{{ item }}"
          loop:
            - "uci commit"
            - "/etc/init.d/firewall reload"
          when: uci_set_result.changed

