---
- name: firewall-config - default basic rules for internet access (DHCP, ping,...) src=wan
  hosts: openwrt-og,openwrt-test
  gather_facts: no

  vars:
    uci_vars:

      ## WAN zone
      - { key: "firewall.zone_wan", value: "zone" }
      - { key: "firewall.zone_wan.name", value: "wan" }
      - { key: "firewall.zone_wan.network", value: "wan" }
      - { key: "firewall.zone_wan.input", value: "DROP" }
      - { key: "firewall.zone_wan.output", value: "ACCEPT" }
      - { key: "firewall.zone_wan.forward", value: "DROP" }
      - { key: "firewall.zone_wan.log", value: "1" }
      - { key: "firewall.zone_wan.masq", value: "1" }
      - { key: "firewall.zone_wan.mtu_fix", value: "1" }

      ## rules
      # DHCP-Renew
      - { key: "firewall.rule_dhcp_renew",      value: "rule" }
      - { key: "firewall.rule_dhcp_renew.name",      value: "ansible_default_DHCP-Renew" }
      - { key: "firewall.rule_dhcp_renew.src",       value: "*" }
      - { key: "firewall.rule_dhcp_renew.proto",     value: "udp" }
      - { key: "firewall.rule_dhcp_renew.dest_port", value: "68" }
      - { key: "firewall.rule_dhcp_renew.target",    value: "ACCEPT" }
      - { key: "firewall.rule_dhcp_renew.family",    value: "ipv4" }

      # Ping
      - { key: "firewall.rule_ping",      value: "rule" }
      - { key: "firewall.rule_ping.name",      value: "ansible_default_Ping" }
      - { key: "firewall.rule_ping.src",       value: "wan" }
      - { key: "firewall.rule_ping.proto",     value: "icmp" }
      - { key: "firewall.rule_ping.icmp_type", value: "echo-request" }
      - { key: "firewall.rule_ping.family",    value: "ipv4" }
      - { key: "firewall.rule_ping.target",    value: "DROP" }

      # IGMP
      - { key: "firewall.rule_igmp",    value: "rule" }
      - { key: "firewall.rule_igmp.name",    value: "ansible_default-IGMP" }
      - { key: "firewall.rule_igmp.src",     value: "*" }
      - { key: "firewall.rule_igmp.proto",   value: "igmp" }
      - { key: "firewall.rule_igmp.family",  value: "ipv4" }
      - { key: "firewall.rule_igmp.target",  value: "ACCEPT" }

      # DHCPv6
      - { key: "firewall.rule_dhcpv6",      value: "rule" }
      - { key: "firewall.rule_dhcpv6.name",      value: "ansible_default-DHCPv6" }
      - { key: "firewall.rule_dhcpv6.src",       value: "*" }
      - { key: "firewall.rule_dhcpv6.proto",     value: "udp" }
      - { key: "firewall.rule_dhcpv6.dest_port", value: "546" }
      - { key: "firewall.rule_dhcpv6.family",    value: "ipv6" }
      - { key: "firewall.rule_dhcpv6.target",    value: "ACCEPT" }

      # MLD
      - { key: "firewall.rule_mld",      value: "rule" }
      - { key: "firewall.rule_mld.name",      value: "ansible_default-MLD" }
      - { key: "firewall.rule_mld.src",       value: "*" }
      - { key: "firewall.rule_mld.proto",     value: "icmp" }
      - { key: "firewall.rule_mld.src_ip",    value: "fe80::/10" }
      - { key: "firewall.rule_mld.icmp_type", value: "130/0 131/0 132/0 143/0" }
      - { key: "firewall.rule_mld.family",    value: "ipv6" }
      - { key: "firewall.rule_mld.target",    value: "ACCEPT" }

      # ICMPv6-Input
      - { key: "firewall.rule_icmpv6_input",      value: "rule" }
      - { key: "firewall.rule_icmpv6_input.name",      value: "ansible_default-ICMPv6-Input" }
      - { key: "firewall.rule_icmpv6_input.src",       value: "wan" }
      - { key: "firewall.rule_icmpv6_input.proto",     value: "icmp" }
      - { key: "firewall.rule_icmpv6_input.icmp_type", value: "echo-request echo-reply destination-unreachable packet-too-big time-exceeded bad-header unknown-header-type router-solicitation neighbour-solicitation router-advertisement neighbour-advertisement" }
      - { key: "firewall.rule_icmpv6_input.limit",     value: "1000/sec" }
      - { key: "firewall.rule_icmpv6_input.family",    value: "ipv6" }
      - { key: "firewall.rule_icmpv6_input.target",    value: "DROP" }

      # ICMPv6-Forward
      - { key: "firewall.rule_icmpv6_forward",      value: "rule" }
      - { key: "firewall.rule_icmpv6_forward.name",      value: "ansible_default-ICMPv6-Forward" }
      - { key: "firewall.rule_icmpv6_forward.src",       value: "wan" }
      - { key: "firewall.rule_icmpv6_forward.dest",      value: "*" }
      - { key: "firewall.rule_icmpv6_forward.proto",     value: "icmp" }
      - { key: "firewall.rule_icmpv6_forward.icmp_type", value: "echo-request echo-reply destination-unreachable packet-too-big time-exceeded bad-header unknown-header-type" }
      - { key: "firewall.rule_icmpv6_forward.limit",     value: "1000/sec" }
      - { key: "firewall.rule_icmpv6_forward.family",    value: "ipv6" }
      - { key: "firewall.rule_icmpv6_forward.target",    value: "DROP" }

      # IPSec-ESP
      - { key: "firewall.rule_ipsec_esp",   value: "rule" }
      - { key: "firewall.rule_ipsec_esp.name",   value: "ansible_default-IPSec-ESP" }
      - { key: "firewall.rule_ipsec_esp.src",    value: "wan" }
      - { key: "firewall.rule_ipsec_esp.dest",   value: "lan" }
      - { key: "firewall.rule_ipsec_esp.proto",  value: "esp" }
      - { key: "firewall.rule_ipsec_esp.target", value: "ACCEPT" }

      # ISAKMP
      - { key: "firewall.rule_isakmp",      value: "rule" }
      - { key: "firewall.rule_isakmp.name",      value: "ansible_default-ISAKMP" }
      - { key: "firewall.rule_isakmp.src",       value: "wan" }
      - { key: "firewall.rule_isakmp.dest",      value: "lan" }
      - { key: "firewall.rule_isakmp.dest_port", value: "500" }
      - { key: "firewall.rule_isakmp.proto",     value: "udp" }
      - { key: "firewall.rule_isakmp.target",    value: "ACCEPT" }


  tasks:
    - name: set uci values if needed
      raw: |
        current=$(uci get {{ item.key }} 2>/dev/null || echo "NOT_SET")
        desired="{{ item.value }}"
        
        if [ "$current" != "$desired" ]
        then
          uci set {{ item.key }}="{{ item.value }}"
          echo "changed"
        else
          echo "unchanged"
        fi
      loop: "{{ uci_vars }}"
      register: uci_set_result
      changed_when: "not 'unchanged' in uci_set_result.stdout"

    - name: apply changes
      block:
        - name: commit enable and restart
          raw: "{{ item }}"
          loop:
            - "uci commit"
            - "/etc/init.d/firewall restart"
          when: uci_set_result.changed

