---
- name: internetaccess for ftth pppoe with vlan7 needed for telekom
  hosts: all
  gather_facts: no

  vars:

    uci_vars:

      # define VLAN 7 (Telekom) over FTTH-WAN-Port
      - { key: "network.wan_7", value: "device" }
      - { key: "network.wan_7.type", value: "8021q" }
      - { key: "network.wan_7.ifname", value: "wan" }
      - { key: "network.wan_7.vid", value: "7" }

      # WAN: PPPoE auf VLAN 7 (Telekom)
      - { key: "network.wan.proto", value: "pppoe" }
      - { key: "network.wan.device", value: "wan.7" }
      - { key: "network.wan.username", value: "{{ pppoe_user }}" }
      - { key: "network.wan.password", value: "{{ pppoe_pw }}" }
      - { key: "network.wan.ipv6", value: "auto" }
      - { key: "network.wan.peerdns", value: "1" }

      # Management for FTTH-Modem on 192.168.100.1
      - { key: "network.wan_mgmt", value: "interface" }
      - { key: "network.wan_mgmt.proto", value: "static" }
      - { key: "network.wan_mgmt.device", value: "wan" }
      - { key: "network.wan_mgmt.ipaddr", value: "192.168.100.220" }
      - { key: "network.wan_mgmt.netmask", value: "255.255.255.0" }
      - { key: "network.wan_mgmt.defaultroute", value: "0" }
      - { key: "network.wan_mgmt.peerdns", value: "0" }


  tasks:

    - name: set uci values if needed
      raw: |
        current=$(uci get {{ item.key }} 2>/dev/null || echo "NOT_SET")
        desired="{{ item.value }}"

        if [ "$current" != "$desired" ]
        then
          uci set {{ item.key }}="{{ item.value }}"
          echo "changed"
        else
          echo "unchanged"
        fi
      loop: "{{ uci_vars }}"
      register: uci_set_result
      changed_when: "not 'unchanged' in uci_set_result.stdout"

    - name: apply changes
      block:
        - name: commit enable and restart
          raw: "{{ item }}"
          loop:
            - "uci commit"
            - "/etc/init.d/network reload"
            - "/etc/init.d/odhcpd restart"
            - "/etc/init.d/odhcpd enable"
          when: uci_set_result.changed


