---
- name: internetaccess for ftth pppoe with vlan7 needed for telekom
  hosts: all
  gather_facts: no

  vars:

    uci_vars:

      # WAN: PPPoE FB LAN1
      - { key: "network.wan.proto", value: "pppoe" }
      - { key: "network.wan.device", value: "wan"}
      - { key: "network.wan.username", value: "{{ pppoe_user }}" }
      - { key: "network.wan.password", value: "{{ pppoe_pw }}" }
      - { key: "network.wan.ipv6", value: "auto" }
      - { key: "network.wan.peerdns", value: "1" }

  tasks:

    - name: set uci values if needed
      raw: |
        current=$(uci get {{ item.key }} 2>/dev/null || echo "NOT_SET")
        desired="{{ item.value }}"

        if [ "$current" != "$desired" ]
        then
          uci set {{ item.key }}="{{ item.value }}"
          echo "changed"
        else
          echo "unchanged"
        fi
      loop: "{{ uci_vars }}"
      register: uci_set_result
      changed_when: "not 'unchanged' in uci_set_result.stdout"

    - name: apply changes
      block:
        - name: commit enable and restart
          raw: "{{ item }}"
          loop:
            - "uci commit"
            - "/etc/init.d/network reload"
            - "/etc/init.d/odhcpd restart"
            - "/etc/init.d/odhcpd enable"
          when: uci_set_result.changed


