---
- name: home-assistant
  hosts: all
  tasks:

    - name: Create /home/docker/home-assistant.{{inventory_hostname}} dir
      ansible.builtin.file:
        path: /home/docker/home-assistant.{{inventory_hostname}}
        owner: root
        group: docker
        state: directory
        mode: '0550'

    - name: Create /home/docker/home-assistant.{{inventory_hostname}}/config dir
      ansible.builtin.file:
        path: /home/docker/home-assistant.{{inventory_hostname}}/config
        owner: 3000
        group: 3000
        state: directory
        mode: '0750'

    - name: Create oidc client secret
      ansible.builtin.shell: |
        /home/docker/authelia.{{inventory_hostname}}/gen-oidc-client-secret.sh /home/docker/home-assistant.{{inventory_hostname}}
      changed_when: false
      failed_when: false

    - name: Edit Home Assistant config
      blockinfile:
        path: /home/docker/home-assistant.{{inventory_hostname}}/config/configuration.yaml
        create: yes
        mode: 0444
        owner: root
        group: docker
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # Loads default set of integrations. Do not remove.
          #default_config:
          homeassistant:
            name: Home
            latitude: 51.1657
            longitude: 10.4515
            elevation: 100
            unit_system: metric
            currency: EUR
            time_zone: Europe/Berlin
            external_url: "https://home-assistant.{{inventory_hostname}}"

          api:
          history:
          logbook:
          system_health:
          ssdp:
          zeroconf:
          sun:
          sensor:
          weather:
          person:
          mobile_app:
          light:
          mqtt:
          tts:
          stream:
          media_source:
                    
          # Load frontend themes from the themes folder
          frontend:
            themes: !include_dir_merge_named themes
          automation: !include automations.yaml
          script: !include scripts.yaml
          scene: !include scenes.yaml
          
          http:
            use_x_forwarded_for: true
            trusted_proxies:
              - 192.168.41.200 # traefik
          
          auth_oidc:
            client_id: 'home-assistant'
            client_secret: '{{ lookup('file', '/home/docker/home-assistant.' + inventory_hostname + '/oidc_password') }}'
            discovery_url: 'https://auth.defiant.dedyn.io/.well-known/openid-configuration'
            display_name: 'Authelia'
            claims:
              groups: 'groups'
            roles:
              admin: 'home-assistant-admin'
              user: 'home-assistant'

        backup: yes
      notify: Restart home-assistant

    - name: Touch HA config files
      ansible.builtin.file:
        path: "/home/docker/home-assistant.{{ inventory_hostname }}/config/{{ item }}"
        state: touch
        access_time: preserve
        modification_time: preserve
      loop:
        - scenes.yaml
        - scripts.yaml
        - automations.yaml

    - name: /home/docker/home-assistant.{{inventory_hostname}}/genpw.sh (generate Random PW for Home Assistant)
      blockinfile:
        path: /home/docker/home-assistant.{{inventory_hostname}}/genpw.sh
        create: yes
        mode: 0550
        owner: root
        group: docker
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          cd /home/docker/home-assistant.{{inventory_hostname}}
          homeassistantadminpassword=$(pwgen -s 32 1)

          [ -f env ] || echo "HA_ADMIN_PASSWORD=!HA_ADMIN_PASSWORD!
          " >env

          chmod 440 env
          chown root:docker env
          sed -i "s/\!HA_ADMIN_PASSWORD\!/$homeassistantadminpassword/g" env
        backup: yes
        validate: /bin/bash -n %s
      notify: run genpw.sh

    - name: /home/docker/home-assistant.{{inventory_hostname}}/genpw.sh shebang
      lineinfile:
        path: /home/docker/home-assistant.{{inventory_hostname}}/genpw.sh
        insertbefore: BOF
        line: "#!/bin/bash -e"

    - name: Gen initial passwords if not exists
      ansible.builtin.shell: ./genpw.sh
      args:
        chdir: /home/docker/home-assistant.{{inventory_hostname}}
        creates: /home/docker/home-assistant.{{inventory_hostname}}/env

    - name: /home/docker/home-assistant.{{inventory_hostname}}/docker-compose.yml Container Configuration
      blockinfile:
        path: /home/docker/home-assistant.{{inventory_hostname}}/docker-compose.yml
        create: yes
        mode: 0440
        owner: root
        group: docker
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          services:
            home-assistant.{{inventory_hostname}}:
              image: ghcr.io/home-assistant/home-assistant
              restart: unless-stopped
              volumes:
                - ./config:/config
                - ./media:/media
                - /etc/localtime:/etc/localtime:ro
                - /run/dbus:/run/dbus:ro
              network_mode: host
              privileged: true

        backup: yes
      notify: Restart home-assistant

    - name: /home/docker/traefik/providers/home-assistant.yml Home-Assistant<->Traefik provider
      blockinfile:
        path: /home/docker/traefik/providers/home-assistant.yml
        create: yes
        mode: 0444
        owner: root
        group: docker
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          http:
            routers:
              home-assistant:
                rule: "Host(`home-assistant.{{inventory_hostname}}`)"
                service: home-assistant
                entryPoints:
                  - "https"
                tls:
                  certresolver: letsencrypt
                middlewares: 
                  - "secHeaders@file"
            services:
              home-assistant:
                loadBalancer:
                  servers:
                    - url: "http://192.168.41.1:8123"


    - name: Create group and add user if not exists
      ansible.builtin.shell: |
        ldapaddgroup home-assistant
        ldapaddgroup home-assistant-admin
        ldapaddusertogroup admin home-assistant-admin
      changed_when: false
      failed_when: false

    - name: Clone hass-oidc-auth repo
      git:
        repo: "https://github.com/christiaangoossens/hass-oidc-auth.git"
        dest: "/tmp/hass-oidc-auth"
        version: "main"

    - name: Create custom_components dir
      file:
        path: "/home/docker/home-assistant.{{inventory_hostname}}/config/custom_components"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Copy hass_oidc_auth component
      copy:
        src: "/tmp/hass-oidc-auth/custom_components/auth_oidc"
        dest: "/home/docker/home-assistant.{{inventory_hostname}}/config/custom_components"
        owner: root
        group: root
        mode: "0644"
      notify: Restart home-assistant

    - name: write OIDC config in authelias configuration.yml
      ansible.builtin.blockinfile:
        path: /home/docker/authelia.{{inventory_hostname}}/authelia-data/configuration.yml
        marker: "# {mark} ANSIBLE MANAGED BLOCK OIDC home-assistant.{{inventory_hostname}}"
        block: |2
                # home-assistant
                - client_id: 'home-assistant'
                  client_name: 'Home Assistant'
                  client_secret: '{{ lookup('file', '/home/docker/home-assistant.' + inventory_hostname + '/oidc_digest') }}'
                  public: false
                  require_pkce: true
                  pkce_challenge_method: 'S256'
                  authorization_policy: '{{ lookup('file', '/home/docker/authelia.' + inventory_hostname + '/authorization_policy') }}'
                  consent_mode: 'implicit'
                  redirect_uris:
                    - 'https://home-assistant.defiant.dedyn.io/auth/oidc/callback'
                  scopes:
                    - 'openid'
                    - 'profile'
                    - 'groups'
                  response_types:
                    - 'code'
                  grant_types:
                    - 'authorization_code'
                  access_token_signed_response_alg: 'none'
                  userinfo_signed_response_alg: 'none'
                  token_endpoint_auth_method: 'client_secret_post'
        insertafter: "^# END ANSIBLE MANAGED BLOCK OIDC"
        backup: yes
        validate: docker run --rm -v "{{ ansible_env.HOME }}/.ansible:{{ ansible_env.HOME }}/.ansible" authelia/authelia:latest authelia validate-config --config %s
      notify: Restart authelia

    - name: Start home-assistant
      ansible.builtin.shell: docker-compose up -d
      args:
        chdir: /home/docker/home-assistant.{{inventory_hostname}}
        creates: /home/docker/home-assistant.{{inventory_hostname}}/config/home-assistant_v2.db
     
    - name: Wait until home-assistant install is finished
      wait_for:
        path: /home/docker/home-assistant.{{inventory_hostname}}/config/home-assistant_v2.db
     
    - name: /home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.sh
      blockinfile:
        path: /home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.sh
        mode: "0500"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # home-assistant
          sleep 30
          cd /home/docker/home-assistant.{{inventory_hostname}} || exit 1
          . ./env
          curl --location --request POST 'http://192.168.43.1:8123/api/onboarding/users' --header 'Content-Type: application/json' --data-raw "{
            \"client_id\": \"http://192.168.43.1:8123/\",
           \"name\": \"admin\",
            \"username\": \"haadmin\",
            \"password\": \"${HA_ADMIN_PASSWORD}\",
            \"language\": \"de\"
          }" >>/home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.log 2>&1
          # install home assistant community store (hacs)
          docker compose exec -ti home-assistant.defiant.dedyn.io wget -O - https://get.hacs.xyz | bash - >>/home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.log 2>&1
        backup: yes
        validate: /bin/bash -n %s
      #notify: run home-assistant.init
    
    - name: Run home-assistant.init after install
      ansible.builtin.shell: bash /home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.sh
      args:
        chdir: /home/docker/home-assistant.{{inventory_hostname}}
        creates: /home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.log

  handlers:
    - name: run genpw.sh
      ansible.builtin.shell: ./genpw.sh
      args:
        chdir: /home/docker/home-assistant.{{inventory_hostname}}
      notify: Restart home-assistant

    #- name: run home-assistant.init
    #  ansible.builtin.shell: bash /home/docker/home-assistant.{{inventory_hostname}}/home-assistant.init.sh

    - name: Restart home-assistant
      ansible.builtin.shell: docker-compose up -d --force-recreate
      args:
        chdir: /home/docker/home-assistant.{{inventory_hostname}}

    - name: Restart authelia
      ansible.builtin.shell: docker-compose down && docker-compose up -d
      args:
        chdir: /home/docker/authelia.{{inventory_hostname}}


