---
- name: Deploy OpenVPN Bridge Mode Server with easy-rsa and ACME auto-renewal
  hosts: all

  vars:
    openvpn_bridge_name: iot0
    openvpn_network: 172.31.0.0/16
    openvpn_server_ip: 172.31.0.1
    openvpn_port: 1194
    openvpn_protocol: udp
    openvpn_cert_days: 30  # Certificates valid for 30 days

  tasks:
    # Install required packages
    - name: Install OpenVPN, easy-rsa, and bridge-utils
      apt:
        name:
          - openvpn
          - easy-rsa
          - bridge-utils
        state: present
        update_cache: yes
        install_recommends: no

    # Configure bridge interface
    - name: Configure bridge interface in /etc/network/interfaces
      blockinfile:
        path: /etc/network/interfaces.d/{{ openvpn_bridge_name }}
        block: |
          auto {{ openvpn_bridge_name }}
          iface {{ openvpn_bridge_name }} inet static
              bridge_ports none
              address {{ openvpn_server_ip }}
              netmask 255.255.0.0
              bridge_fd 0
              bridge_maxwait 0
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        create: yes

    - name: Create /etc/openvpn/easy-rsa
      ansible.builtin.file:
        path: /etc/openvpn/easy-rsa
        owner: root
        group: root
        state: directory
        mode: '0750'

    # Initialize easy-rsa PKI
    - name: Initialize easy-rsa PKI
      command: >
        /usr/share/easy-rsa/easyrsa --batch init-pki
        chdir=/etc/openvpn/easy-rsa
        creates=/etc/openvpn/easy-rsa/pki

    # Build CA (valid for 30 days)
    - name: Build CA with 30 days validity
      command: >
        /usr/share/easy-rsa/easyrsa --batch --days={{ openvpn_cert_days }} build-ca nopass
        chdir=/etc/openvpn/easy-rsa
        creates=/etc/openvpn/easy-rsa/pki/ca.crt

    # Generate DH parameters
    - name: Generate Diffie-Hellman parameters
      command: >
        /usr/share/easy-rsa/easyrsa --batch gen-dh
        chdir=/etc/openvpn/easy-rsa
        creates=/etc/openvpn/easy-rsa/pki/dh.pem

    # Generate server certificate (valid for 30 days)
    - name: Generate server certificate with 30 days validity
      command: >
        /usr/share/easy-rsa/easyrsa --batch --days={{ openvpn_cert_days }} build-server-full openvpn-server nopass
        chdir=/etc/openvpn/easy-rsa
        creates=/etc/openvpn/easy-rsa/pki/issued/openvpn-server.crt

    # Copy server keys and certs to OpenVPN directory
    - name: Copy server keys and certs to OpenVPN directory
      copy:
        src: "/etc/openvpn/easy-rsa/pki/{{ item.src }}"
        dest: "/etc/openvpn/{{ item.dest }}"
        remote_src: yes
      loop:
        - { src: "ca.crt", dest: "ca.crt" }
        - { src: "private/openvpn-server.key", dest: "server.key" }
        - { src: "issued/openvpn-server.crt", dest: "server.crt" }
        - { src: "dh.pem", dest: "dh.pem" }

    # Configure OpenVPN server (bridge mode)
    - name: Configure OpenVPN server in bridge mode
      copy:
        dest: /etc/openvpn/server.conf
        content: |
          port {{ openvpn_port }}
          proto {{ openvpn_protocol }}
          dev tap
          ca ca.crt
          cert server.crt
          key server.key
          dh dh.pem
          server-bridge {{ openvpn_server_ip }} 255.255.0.0 {{ openvpn_network | ipaddr('net') | ipaddr('1') }} {{ openvpn_network | ipaddr('net') | ipaddr('254') }}
          push "route {{ openvpn_network }} 255.255.0.0"
          keepalive 10 120
          cipher AES-256-CBC
          auth SHA256
          user nobody
          group nogroup
          persist-key
          persist-tun
          status openvpn-status.log
          verb 3
          explicit-exit-notify 1

    # Enable and start OpenVPN service
    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn@server
        enabled: yes
        state: started

    - name: Allow port from all IPv4/IPv6 private networks
      community.general.ufw:
        rule: allow
        port: "{{ openvpn_port }}"
        proto: "{{ openvpn_protocol }}"
        src: "{{ item }}"
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7

    # Restart networking to apply bridge
    - name: Restart networking to apply bridge
      service:
        name: networking
        state: restarted


