---
- name: Deploy OpenVPN Bridge Mode Server with easy-rsa and ACME auto-renewal
  hosts: all

  vars:
    openvpn_bridge_name: iot0
    openvpn_network: 172.31.0.0/16
    openvpn_server_ip: 172.31.0.1
    openvpn_port: 1194
    openvpn_protocol: udp
    openvpn_cert_days: 30  # Certificates valid for 30 days
    easyrsa_path: /etc/openvpn/iot-easy-rsa

  tasks:
    # Install required packages
    - name: Install OpenVPN, easy-rsa, and bridge-utils
      apt:
        name:
          - openvpn
          - easy-rsa
          - bridge-utils
        state: present
        update_cache: yes
        install_recommends: no

    # Configure bridge interface
    - name: Configure bridge interface in /etc/network/interfaces
      blockinfile:
        path: /etc/network/interfaces.d/{{ openvpn_bridge_name }}
        block: |
          auto {{ openvpn_bridge_name }}
          iface {{ openvpn_bridge_name }} inet static
              bridge_ports none
              address {{ openvpn_server_ip }}
              netmask 255.255.0.0
              bridge_fd 0
              bridge_maxwait 0
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        create: yes
      notify: restart networking to apply bridge

    - name: Create easyrsa_path
      ansible.builtin.file:
        path: "{{ easyrsa_path }}"
        owner: root
        group: root
        state: directory
        mode: '0750'

    - name: Run easy-rsa PKI steps
      command: >
        /usr/share/easy-rsa/easyrsa --batch {{ item.cmd }}
      args:
        chdir: "{{ easyrsa_path }}"
        creates: "{{ easyrsa_path }}/{{ item.creates }}"
      loop:
        - { cmd: 'init-pki', creates: 'pki' }
        - { cmd: '--days={{ openvpn_cert_days }} build-ca nopass', creates: 'pki/ca.crt' }
        - { cmd: 'gen-dh', creates: 'pki/dh.pem' }
        - { cmd: '--days={{ openvpn_cert_days }} build-server-full openvpn-server nopass', creates: 'pki/issued/openvpn-server.crt' }
      notify: restart openvpn

    # Configure OpenVPN server (bridge mode)
    - name: Configure OpenVPN server in bridge mode
      blockinfile:
        path: /etc/openvpn/iot.conf
        mode: "0444"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          port {{ openvpn_port }}
          proto {{ openvpn_protocol }}
          dev tap
          ca {{ easyrsa_path }}/pki/ca.crt
          cert {{ easyrsa_path }}/pki/issued/openvpn-server.crt
          key {{ easyrsa_path }}/pki/private/openvpn-server.key
          dh {{ easyrsa_path }}/pki/dh.pem
          server-bridge
          keepalive 10 120
          cipher AES-256-CBC
          auth SHA256
          user nobody
          group nogroup
          persist-key
          persist-tun
          status /var/log/openvpn/iot-status.log
          verb 3
          explicit-exit-notify 1
          script-security 2
          up /etc/openvpn/iot-dev2bridge.sh
          log-append /var/log/openvpn/iot.log
        backup: yes
      notify: restart openvpn

    - name: bridge script for openvpn
      blockinfile:
        path: /etc/openvpn/iot-dev2bridge.sh
        mode: "0500"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # OpenVPN Up Script to add tap to bridge
          # get dynamically added tap device
          tap=$dev

          # set tap interface up without IP
          /sbin/ip link set dev $tap up
          /sbin/ip addr flush dev $tap

          # add tap interface to bridge iot0
          /sbin/ip link set dev $tap master iot0

          # set promisc mode for tap
          /sbin/ip link set dev $tap promisc on
        backup: yes
        validate: /bin/bash -n %s
      notify: restart openvpn

    - name: /etc/openvpn/iot-dev2bridge.sh shebang
      lineinfile:
        path: /etc/openvpn/iot-dev2bridge.sh
        insertbefore: BOF
        line: "#!/bin/bash"

    - name: /usr/local/bin/ovpn-client-add.sh
      blockinfile:
        path: /usr/local/bin/ovpn-client-add.sh
        mode: "0500"
        owner: root
        group: root
        create: yes
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          # Config
          EASYRSA_DIR="{{ easyrsa_path }}"
          OPENVPN_DIR="/etc/openvpn"
          CLIENT_NAME="${1}.iot"
          CERT_DAYS=30

          if [ -z "$CLIENT_NAME" ]; then
            echo "Usage: $0 <client-name>"
            exit 1
          fi

          cd "$EASYRSA_DIR" || exit 1

          # create client cert and key
          /usr/share/easy-rsa/easyrsa --batch --days="$CERT_DAYS" build-client-full "$CLIENT_NAME" nopass || exit 2

          # needed files
          CA_CRT="$EASYRSA_DIR/pki/ca.crt"
          CLIENT_CRT="$EASYRSA_DIR/pki/issued/$CLIENT_NAME.crt"
          CLIENT_KEY="$EASYRSA_DIR/pki/private/$CLIENT_NAME.key"

          # generate .ovpn-file
          cat > "${CLIENT_NAME}.ovpn" <<EOF
          client
          dev tap
          proto udp
          remote defiant.dedyn.io 1194
          resolv-retry infinite
          nobind
          persist-key
          persist-tun
          ca [inline]
          cert [inline]
          key [inline]
          cipher AES-256-CBC
          auth SHA256
          verb 3
          remote-cert-tls server
          script-security 2
          up /etc/openvpn/iot-dev2bridge.sh

          <ca>
          $(cat "$CA_CRT")
          </ca>
          <cert>
          $(cat "$CLIENT_CRT")
          </cert>
          <key>
          $(cat "$CLIENT_KEY")
          </key>
          EOF

          echo "${EASYRSA_DIR}/${CLIENT_NAME}.ovpn created"
        backup: yes
        validate: /bin/bash -n %s
      notify: restart openvpn

    - name: /usr/local/bin/ovpn-client-add.sh shebang
      lineinfile:
        path: /usr/local/bin/ovpn-client-add.sh
        insertbefore: BOF
        line: "#!/bin/bash"

    # Enable and start OpenVPN service
    - name: Enable and start OpenVPN service
      systemd:
        name: openvpn@iot
        enabled: yes
        state: started

    - name: Allow port from all IPv4/IPv6 private networks
      community.general.ufw:
        rule: allow
        port: "{{ openvpn_port }}"
        proto: "{{ openvpn_protocol }}"
        src: "{{ item }}"
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - fc00::/7

  handlers:

    # restart networking to apply bridge
    - name: restart networking to apply bridge
      service:
        name: networking
        state: restarted
      notify: restart openvpn

    - name: restart openvpn
      service:
        name: openvpn@iot
        state: restarted
